# TCL File Generated by Component Editor 21.1
# Wed Apr 29 13:46:25 EDT 2026
# DO NOT MODIFY


# 
# nbody_accel_avmm "N-body Accelerator" v1.0
#  2026.04.29.13:46:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module nbody_accel_avmm
# 
set_module_property DESCRIPTION ""
set_module_property NAME nbody_accel_avmm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "N-body Accelerator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "nbody_accel_avmm"
set_module_assignment embeddedsw.dts.group "nbody"


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nbody_accel_avmm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FpAdd.sv SYSTEM_VERILOG PATH code/FpAdd.sv
add_fileset_file FpInvSqrt.sv SYSTEM_VERILOG PATH code/FpInvSqrt.sv
add_fileset_file FpMul.sv SYSTEM_VERILOG PATH code/FpMul.sv
add_fileset_file FpNegate.sv SYSTEM_VERILOG PATH code/FpNegate.sv
add_fileset_file four_core_wrapper.sv SYSTEM_VERILOG PATH code/four_core_wrapper.sv
add_fileset_file fourcore_bcj_datapath.sv SYSTEM_VERILOG PATH code/fourcore_bcj_datapath.sv
add_fileset_file nbody_accel_avmm.sv SYSTEM_VERILOG PATH code/nbody_accel_avmm.sv TOP_LEVEL_FILE
add_fileset_file nbody_control.sv SYSTEM_VERILOG PATH code/nbody_control.sv
add_fileset_file nbody_integrator.sv SYSTEM_VERILOG PATH code/nbody_integrator.sv
add_fileset_file nbody_mem.sv SYSTEM_VERILOG PATH code/nbody_mem.sv
add_fileset_file two_body_core.sv SYSTEM_VERILOG PATH code/two_body_core.sv


# 
# parameters
# 
add_parameter MAX_BODIES INTEGER 256 ""
set_parameter_property MAX_BODIES DEFAULT_VALUE 256
set_parameter_property MAX_BODIES DISPLAY_NAME MAX_BODIES
set_parameter_property MAX_BODIES WIDTH ""
set_parameter_property MAX_BODIES TYPE INTEGER
set_parameter_property MAX_BODIES UNITS None
set_parameter_property MAX_BODIES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_BODIES DESCRIPTION ""
set_parameter_property MAX_BODIES HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group nbody
set_module_assignment embeddedsw.dts.name nbody_accel_avmm
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 address address Input 8
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

